### ISSUE TITLE
One the Players Screen is Locked, How Does GM Move the Players Screen?

### ISSUE THREAD

**Issue by jabbamonkey** [MaterialFoundry/LockView#112]
I was looking for a way to run Foundry on a tabletop screen (and many people said use LockView). I have a laptop, connected to my tabletop screen via an HDMI cable. I have everything set so the "player" (the tabletop tv .... which is a browser window, running Foundry from a "player" account,) can't move the map. That's great. However, for REALLY large maps, the DM needs to move the map (on the TV, or the player's account) so everyone at the table can see the other areas of the map.  Note: As the DM, I can move the map and look all over the place when logged in as the gamemaster (which has all my notes, monsters, etc) .... but the player account, running on the TV screen, is completely fixed.

The only way I have to resolve this now, is load the map .... and when the players get to the TVs edge, I _configure_ the _scene_, change the _initial view position_, and then reload the map. (a real pain if you dont already have the new position coordinates already noted somewhere).

Is there another way to do this? 

Below are my current USER SETTINGS ... in case that is wrong.
![UserSettings](https://github.com/MaterialFoundry/LockView/assets/1598407/c21782a8-32c4-45d8-8106-a0cc3cb58965)

**Comment by MaterialFoundry** [comment]
I think you're looking for the 'Edit Viewbox' functionality of the module, see the documentation: https://github.com/MaterialFoundry/LockView/wiki/Controls#viewbox
