### ISSUE TITLE
[BUG] Please update for Foundry v12

### ISSUE THREAD

**Issue by mazirian** [MaterialFoundry/LockView#116]
- OS: [Windows]
 - Browser: [Chrome/Brave]
 - Module version: [e.g. 1.5.9]
 - Foundry version: [12 build 327]
 - Gaming system & version: [pf2e 6.0.1]
 - Any other modules enabled: [yes]

**Describe the bug**
Existing scenes that were setup with LockView still respect any settings that were applied (lock scroll/ pan etc.
But it is no longer possible to change the settings on a scene because the lockview tab is not displaying them.

**Screenshots**
![image](https://github.com/MaterialFoundry/LockView/assets/1999902/75fd614e-b10a-4cd2-9236-9301be601dda)

**Console Log**
No errors in the console log only deprecation warnings.

**Comment by MaterialFoundry** [comment]
I've just released a new version that's compatible with v12
