### ISSUE TITLE
Gamemaster not able to Zoom while using Lock View in The Forge for FoundryVTT

### ISSUE THREAD

**Issue by Conradhowlf** [MaterialFoundry/LockView#117]
**Setup**
 - OS: Windows 11
 - Browser: Chrome, ForgeVTT
 - Module version:  1.5.9
 - Foundry version: 11.315
 - Gaming system & version: DnD5e 3.1.2
 - Any other modules enabled: No

**Describe the bug**
Normally, when using Lockview, the view is locked for the players, but no for the Gamemaster, in this bug, the Gamemaster isn't able to Zoom out just like the players

**Console Log**
No Errors

**Comment by MaterialFoundry** [comment]
Could you go into the user config in the module settings and check that 'Enable' isn't checked for the GM? If not, could you check it, save the settings, and then uncheck it and see if it persists.

**Comment by Conradhowlf** [comment]
It worked, I disabled everything and reenabled and it started working for some reason.
Such a easy fix, crazy.
I asked around on all discords I had no one could help me with that, thanks
